<?php ?>
      <div data-role="footer" data-theme="f" class="container footer cf">
        <ul class="content-info">
          <li class="content-info-item content-info-copyright size1of2 unit"><a href="https://atelierbramdehaan.nl/" class="content-info-link unit">Atelier Bram de Haan &middot; 2012 - <?=  date("Y"); ?></a></li>
          <li class="content-info-item size1of2 unit-right"><a href="https://jquerymobile.com/" class="content-info-link content-info-resource unit-right">powered by: <i>jQuery mobile</i></a></li>
        </ul>
      </div>
    </div>
  <script src="<?= $assetPath; ?>js/typeface-tester-v3.min.js"></script>
  </body>
</html>
